services:
  - type: web
    name: loan-approval-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11